import * as React from "react";
import Box from "@mui/material/Box";
import { DataGrid, GridToolbar } from "@mui/x-data-grid";
import { Container, CssBaseline } from "@mui/material";

const columns = [
  {
    field: "id",
    headerName: "ID",
    width: 50,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "name",
    headerName: "Nombre",
    width: 100,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "lastName",
    headerName: "Apellido",
    width: 100,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "email",
    headerName: "Email",
    width: 220,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "dni",
    headerName: "DNI",
    typeof: "number",
    width: 100,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "medicalReg",
    headerName: "Matrícula",
    typeof: "number",
    width: 80,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "bDate",
    headerName: "Fecha Nacimiento",
    width: 150,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "status",
    headerName: "Estado",
    width: 80,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "",
    headerName: "Otro Dato",
    width: 100,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "",
    headerName: "Otro Dato",
    width: 100,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
];

const rows = [
  {
    id: 1,
    lastName: "Smith",
    name: "John",
    age: 29,
    email: "john@example.com",
    medicalReg: "56789",
    dni: "12345678",
    bDate: "18/06/1993",
  },
  {
    id: 2,
    lastName: "Johnson",
    name: "Emma",
    age: 25,
    email: "emma@example.com",
    medicalReg: "87654",
    dni: "87654321",
    bDate: "22/11/1996",
  },
  {
    id: 3,
    lastName: "Brown",
    name: "Michael",
    age: 38,
    email: "michael@example.com",
    medicalReg: "23456",
    dni: "76543210",
    bDate: "05/03/1984",
  },
  {
    id: 4,
    lastName: "Davis",
    name: "Olivia",
    age: 31,
    email: "olivia@example.com",
    medicalReg: "98765",
    dni: "54321098",
    bDate: "12/09/1990",
  },
  {
    id: 5,
    lastName: "Miller",
    name: "William",
    age: 45,
    email: "william@example.com",
    medicalReg: "87654",
    dni: "10987654",
    bDate: "30/07/1977",
  },
  {
    id: 6,
    lastName: "Wilson",
    name: "Sophia",
    age: 27,
    email: "sophia@example.com",
    medicalReg: "34567",
    dni: "87654321",
    bDate: "15/01/1995",
  },
  {
    id: 7,
    lastName: "Moore",
    name: "James",
    age: 33,
    email: "james@example.com",
    medicalReg: "87654",
    dni: "65432109",
    bDate: "03/07/1989",
  },
  {
    id: 8,
    lastName: "Taylor",
    name: "Isabella",
    age: 29,
    email: "isabella@example.com",
    medicalReg: "78965",
    dni: "32109876",
    bDate: "20/04/1993",
  },
  {
    id: 9,
    lastName: "Anderson",
    name: "Alexander",
    age: 36,
    email: "alexander@example.com",
    medicalReg: "67890",
    dni: "21098765",
    bDate: "08/11/1985",
  },
  {
    id: 10,
    lastName: "Thomas",
    name: "Emily",
    age: 22,
    email: "emily@example.com",
    medicalReg: "56789",
    dni: "98765432",
    bDate: "29/02/2000",
  },
  {
    id: 11,
    lastName: "Martinez",
    name: "Liam",
    age: 24,
    email: "liam@example.com",
    medicalReg: "12345",
    dni: "87654321",
    bDate: "11/05/1997",
  },
  {
    id: 12,
    lastName: "Garcia",
    name: "Sophia",
    age: 29,
    email: "sophia@example.com",
    medicalReg: "23456",
    dni: "12345678",
    bDate: "08/09/1992",
  },
  {
    id: 13,
    lastName: "Rodriguez",
    name: "Ethan",
    age: 35,
    email: "ethan@example.com",
    medicalReg: "56789",
    dni: "56789012",
    bDate: "13/02/1987",
  },
  {
    id: 14,
    lastName: "Hernandez",
    name: "Ava",
    age: 27,
    email: "ava@example.com",
    medicalReg: "87654",
    dni: "34567890",
    bDate: "19/10/1994",
  },
  {
    id: 15,
    lastName: "Lopez",
    name: "Noah",
    age: 31,
    email: "noah@example.com",
    medicalReg: "78965",
    dni: "78901234",
    bDate: "27/04/1990",
  },
  {
    id: 16,
    lastName: "Gonzalez",
    name: "Olivia",
    age: 26,
    email: "olivia@example.com",
    medicalReg: "43210",
    dni: "89012345",
    bDate: "16/11/1995",
  },
  {
    id: 17,
    lastName: "Perez",
    name: "Liam",
    age: 30,
    email: "liam@example.com",
    medicalReg: "56789",
    dni: "12345678",
    bDate: "21/03/1991",
  },
  {
    id: 18,
    lastName: "Sanchez",
    name: "Emma",
    age: 28,
    email: "emma@example.com",
    medicalReg: "87654",
    dni: "56789012",
    bDate: "04/08/1993",
  },
  {
    id: 19,
    lastName: "Gomez",
    name: "Aiden",
    age: 33,
    email: "aiden@example.com",
    medicalReg: "23456",
    dni: "34567890",
    bDate: "10/12/1988",
  },
  {
    id: 20,
    lastName: "Rivera",
    name: "Isabella",
    age: 29,
    email: "isabella@example.com",
    medicalReg: "56789",
    dni: "78901234",
    bDate: "27/06/1992",
  },
  {
    id: 21,
    lastName: "Ramirez",
    name: "Mia",
    age: 25,
    email: "mia@example.com",
    medicalReg: "12345",
    dni: "56789012",
    bDate: "14/09/1996",
  },
  {
    id: 22,
    lastName: "Torres",
    name: "Elijah",
    age: 36,
    email: "elijah@example.com",
    medicalReg: "34567",
    dni: "67890123",
    bDate: "09/02/1985",
  },
  {
    id: 23,
    lastName: "Flores",
    name: "Scarlett",
    age: 30,
    email: "scarlett@example.com",
    medicalReg: "56789",
    dni: "89012345",
    bDate: "22/05/1991",
  },
  {
    id: 24,
    lastName: "Gutierrez",
    name: "Lucas",
    age: 27,
    email: "lucas@example.com",
    medicalReg: "87654",
    dni: "90123456",
    bDate: "07/10/1994",
  },
  {
    id: 25,
    lastName: "Reyes",
    name: "Harper",
    age: 28,
    email: "harper@example.com",
    medicalReg: "23456",
    dni: "34567890",
    bDate: "18/11/1993",
  },
  {
    id: 26,
    lastName: "Morales",
    name: "Avery",
    age: 32,
    email: "avery@example.com",
    medicalReg: "56789",
    dni: "56789012",
    bDate: "01/06/1989",
  },
  {
    id: 27,
    lastName: "Ortiz",
    name: "Jackson",
    age: 29,
    email: "jackson@example.com",
    medicalReg: "78965",
    dni: "67890123",
    bDate: "12/03/1992",
  },
  {
    id: 28,
    lastName: "Vargas",
    name: "Ella",
    age: 34,
    email: "ella@example.com",
    medicalReg: "87654",
    dni: "89012345",
    bDate: "05/08/1987",
  },
  {
    id: 29,
    lastName: "Castillo",
    name: "Logan",
    age: 26,
    email: "logan@example.com",
    medicalReg: "87654",
    dni: "90123456",
    bDate: "28/07/1995",
  },
  {
    id: 30,
    lastName: "Chavez",
    name: "Grace",
    age: 30,
    email: "grace@example.com",
    medicalReg: "12345",
    dni: "56789012",
    bDate: "09/11/1991",
  },
];

export default function Dashboard() {
  return (
    <Container component="main" sx={{ marginTop: 5, marginBottom: 5 }}>
      <CssBaseline />

      <Box sx={{ height: 400, width: "100%"  }}>
        <DataGrid
          sx={{
            boxShadow: 3,
            border: 2,
            borderColor: '#799A3D',
            '& .MuiDataGrid-cell:hover': {
              color: '#283583',
            },
          }}
          rows={rows}
          columns={columns}
          initialState={{
            pagination: { paginationModel: { pageSize: 10 } },
            filter: {
              filterModel: {
                items: [],
                quickFilterValues: [""],
              },
            },
          }}
          disableColumnFilter
          disableColumnSelector
          disableDensitySelector
          slots={{ toolbar: GridToolbar }}
          slotProps={{
            toolbar: {
              showQuickFilter: true,
              quickFilterProps: { debounceMs: 500 },
            },
          }}
          pageSizeOptions={[10, 20, 30, 40]}
        />
      </Box>
    </Container>
  );
}
